### PR TITLE
add --retina flag

### PR DESCRIPTION
**Pull request by aaronjanse**

### CODE REVIEW

**Comment by ddorn** [comment]
I think you will need to update somethining in get_mouse_pos (at least it was needed in the debugger)

**Comment by aaronjanse** [comment]
Oh, good point.
I'll do that

**Comment by aaronjanse** [comment]
Fixed.
Idk why github shows a merge commit message for the fix, but everything is working in retina mode now

**Comment by ddorn** [comment]
Nice job ! :D

**Pull request merged**
